services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            DB_DATABASE: your_db_name
            DB_PASSWORD: your_password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            -   "3306:3306"

volumes:
    db_data:
