services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        volumes:
            - db_data:/var/lib/mysql
        ports:
            -   "3306:3306"

volumes:
    db_data:
